export const GET_REVIEWS = 'GET_REVIEWS'

export const ADD_REVIEW = 'ADD_REVIEW'

export const DELETE_REVIEW = 'DELETE_REVIEW'

export const EDIT_REVIEW = 'EDIT_REVIEW'

export const SET_ADD_REVIEW_STATE = 'SET_ADD_REVIEW_STATE'

export const TOGGLE_ISEDITING = 'TOGGLE_ISEDITING'

export const REVIEWS_LOADING = 'REVIEWS_LOADING'

export const REVIEWS_FAILURE = 'REVIEWS_FAILURE'
