export const LOADING = 'LOADING'
export const FAILURE = 'FAILURE'

export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const PUT_PROFILE_SUCCESS = 'PUT_PROFILE_SUCCESS'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const SET_SETTINGS_STATE = 'SET_SETTINGS_STATE'
