export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
// export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOADING = 'LOADING'
export const FAILURE = 'FAILURE'

export const SIGNUP = 'SIGNUP'

export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'
// export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE'

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
// export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
// export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
