export const GET_SPACES = 'GET_SPACES'

export const GET_MY_SPACES = 'GET_MY_SPACES'

export const ADD_SPACE = 'ADD_SPACE'

export const DELETE_SPACE = 'DELETE_SPACE'

export const EDIT_SPACE = 'EDIT_SPACE'

export const SET_ADD_SPACE_STATE = 'SET_ADD_SPACE_STATE'

export const TOGGLE_ISEDITING = 'TOGGLE_ISEDITING'

export const SPACES_LOADING = 'SPACES_LOADING'

export const SPACES_FAILURE = 'SPACES_FAILURE'

export const SET_CURRENT_SPACE = 'SET_CURRENT_SPACE'
