export const ADD_PROJECT = 'ADD_PROJECT'

export const SET_ADD_PROJECT_STATE = 'SET_ADD_PROJECT_STATE'

export const DELETE_PROJECT = 'DELETE_PROJECT'

export const EDIT_PROJECT = 'EDIT_PROJECT'

export const TOGGLE_ISEDITING = 'TOGGLE_ISEDITING'
